# -*- coding: utf-8 -*-
"""Sude_Soydan_Midterm.ipynb adlı dosyanın kopyası

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1oStI4nt3Nwp-jM6PCz7UDf87m_vBuo4E

*Hello*, please change the file name as your name_surname_MIDTERM.ipynb and upload to the folder 'DROP MIDTERMS HERE' on Drive.
ex: atay_ilgun_MIDTERM.ipynb

Describe what ML is in 50 words.
"""

Machine Learning is a system which investigates the works and construction of algorithms which can make estimation through data. It works by constructing a model to perform data-based estimates and decisions from sample inputs. Machine learning is the basic learning path by many companies to make more profitable business, increase company growth, optimize processes easily and increase customer satisfaction.

"""Give 3 examples of ML in practical use in todays world - also, meditate on how it is being utilised as well."""

One of example is Siri. It is a smart assistant and it makes easier for people to learn somethings faster and easier. It works with voice command. 
Second one is Spotify. It is a music platform that serves online with the list of current music.
Third one is Netflix. It is a video service that people can access and watch over a wide range of video content at any time.

"""In ML terminology what is an 'example', 'feature', 'label' and 'feature vector'?"""

Example is one part of a data set.
Features is an input variable used in making predictions. is an individual measurable property
Label is in supervised learning, the "answer" or "result" portion of an example.
Feature vector is to represent numeric or symbolic characteristics way.

"""In 100 words meditate on how future advancements on AI could affect your work practice as a communication designer."""

Artificial intelligence will be particularly effective in user experience. Nowadays, it is very effective especially in Social Media. For example, in Facebook News Feed uses machine learning to personalize each individuals feed. When a person stops scrolling to read or like a friends posts, News Feed will start showing more of your friends activity earlier in the feed. So it is a way of Artificial intelligence will be particularly effective in user experience. Nowadays, it is very effective especially in Social Media. For example, in Facebook News Feed uses machine learning to personalize each individuals feed. When a person stops scrolling to read or like a friends posts, News Feed will start showing more of your friends activity earlier in the feed. So it is a way of shown to post for him / her according to the user's likes

"""Try to describe how you learn in algorithmic terms."""

I learned with the used data input and output on the computer.

"""Create a python dictionary for your name surname and year of birth."""

ss = {"name": "sude", "surname": "soydan", "birthyear": "1995"}

"""Write a conditional so If the first letter of your name is 'a' print 'my initial is a!'"""

if ss["name"][0] == "a":
  print("my initial is a")

"""Write a conditional so If your surnames letter count is divisable by 3 print 'it is divisible' if not 'not divisible'."""

if len(ss["surname"]) % 3 == 0:
  print("it is divisible")
else:
  print("it is divisible")

"""Change your year of birth to 2678."""

ss["birthyear"] = 2678
print(ss)

"""Create a loop that goes through 20 to 40 and prints out the numbers that are divisble by 5."""

list_1 = range(20,40)

for everynumber in list_1:
  if everynumber % 5==0:
    print(everynumber)

"""Check the PDF on the Drive and calculate the neurons. Put all neurons and weights in python and do the calculation with them."""

print(0.87*0.06 + 0.12*0.12 + 0.62*0.47)

"""Using the code here:
https://github.com/anishathalye/neural-style
create a ***style transfer*** image.

Upload it along with this file.

You might need a file while doing this, it also is on the Drive!
"""